catalogo/urls.py
from django.urls import path
from . import views
from django.contrib import admin #Aunque no se vé el uso del admin aquí, si no lo importo se presenta la excepción "LookupError: No installed app with label 'admin'".

urlpatterns = [path('', views.inicio, name='vistaHome'), path('libros/', views.LibroVistaLista.as_view(), name='todosLoslibros'), path('libros/conbarbara', views.LibroVistaListaConBarbara.as_view(), name='librosConBarbara'), path('libro/<int:pk>', views.VistaDetalleLibro.as_view(), name='detallesDeLibro'), path('autores/', views.VistaListaGenAutores.as_view(), name='toditicosLosAutores'), path('autor/<int:pk>', views.VistaDetalladaGenAutor.as_view(), name='autorDetalles'), path('reseteoContSesiones', views.borrarConteoVisitas, name='resetearVisitas'),]

urlpatterns += [
    path('LibrosEnManosDelUsuario/<str:username>', views.ListaLibrosPrestadosAlUsuario.as_view(), name='misLibrosalquilados'),
]
#Note la variable de url para url dinámica, <str:username>
urlpatterns += [
    path('TodosLosLibrosActualmenteAlquilados/', views.ListaDeLibrosPrestadosActualmente.as_view(), name='librosAlquiladosActualmente'),
]

urlpatterns += [
    path('libro/<uuid:claveprimaria>/renovacion/', views.renovacionLibroPorLibrero, name='renovDeLibroPorLibrero'),
]

urlpatterns += [
    path('autor/crear/', views.CrearAutor.as_view(), name='crearautorini'),
    path('autor/<int:pk>/actualizar/', views.ActualizarAutor.as_view(), name='actualizarEsteAutor'), path('autor/<int:pk>/borrar/', views.BorrarAutor.as_view(), name='borrar-autor'),]
# Debemos usar pk como el nombre de nuestro valor de clave principal (primary key) capturado, ya que este es el nombre del parámetro esperado por las clases de vista de ediciones genéricas implementadas para ello.

urlpatterns += [
    path('libro/crear/', views.CrearLibro.as_view(), name='crearlibro'),
    path('libro/<int:pk>/actualizar/', views.ActualizarLibro.as_view(), name='actualizarLibro'), path('libro/<int:pk>/borrar/', views.BorrarLibro.as_view(), name='borrarlibro'),]

#Esta vista dejó de trabajar repentinamente:
#urlpatterns += [path('listaLibroautor/', views.VistaCombAutorLibro.as_view(), name='vistaListaLibrosAutor'),]

urlpatterns += [path('ejemUsoSelectOptionsW3.css/', views.librosDelAutor, name='vistaLibrosDelAutor'),]

urlpatterns += [path('librosDelAutor/<str:argumento>', views.formularioLibrosDelAutor, name='vistaLibrosDelAutorFormulario'),]

librerialocal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
from django.conf import settings
# Use static() to add url mapping to serve static files during development (only)
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),path('catalogo/', include('catalogo.urls')),path('', RedirectView.as_view(url='/catalogo/', permanent=True)),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),]
#El nombre url accounts no puede ser arbitrario, porque django en sus vistas genéricas utiliza este nombre en su implementación.

catalogo/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


# Create your models here.

class Genero(models.Model):
    """
    Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.).
    """
    nombre = models.CharField(max_length=200, help_text="Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.)")

    def __str__(self):
        """
        Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)
        """
        return self.nombre

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Libro(models.Model):
    """
    Modelo que representa un libro (pero no un Ejemplar específico).
    """
    titulo = models.CharField(max_length=200)
    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
    descripcion = models.TextField(max_length=1000, help_text="Ingrese una breve descripción del libro")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genero = models.ManyToManyField(Genero, help_text="Seleccione un genero para este libro")
    lenguaje = models.ForeignKey('Lenguaje', on_delete=models.SET_NULL, null=True)
   
    def __str__(self):
        """
        String que representa al objeto Book
        """
        return self.titulo
#El método get_absolute_url para usarlo en las plantillas como href="{{ objeto.get_absolute_url }}", es generalmente preferible porque crea dinamicamente URLs más genéricas y fáciles de mantener en el código del modelo,
#mientras que la etiqueta {% url 'nombreRefDelaUrlEnPath' objeto.id %} es una forma directa de usar estas URLs dentro de las plantillas. get_absolute_url() se enfoca en la lógica de la URL en
#el modelo y es esencial para la integración con la aplicación de administración de Django y la generación de enlaces absolutos:
    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Book
        """
        return reverse('detallesDeLibro', args=[str(self.id)])

    class Meta:
        ordering = ['titulo', 'autor']

    def mostrar_genero(self):
    #Creates a string for tre in Admin.
        return ', '.join([ genero.nombre for genero in self.genero.all()[:3] ]) 

    mostrar_genero.short_description = 'Genero'

import uuid # Requerida para las instancias de libros únicos
from django.core.validators import MaxValueValidator, MinValueValidator 

class LibroInstancia(models.Model):
    """
    Modelo que representa una copia específica de un libro (i.e. que puede ser prestado por la biblioteca).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este libro particular en toda la biblioteca")
    libro = models.ForeignKey('Libro', on_delete=models.SET_NULL, null=True)
    imprenta = models.CharField(max_length=200)
    debidoderegresar = models.DateField(null=True, blank=True)
    prestatario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    PRESTAMO_STATUS = (
        ('m', 'Mantenimieno'),
        ('p', 'En prestamo'),
        ('d', 'Disponible'),
        ('r', 'Reservado'),
    )

    estatus = models.CharField(max_length=1, choices=PRESTAMO_STATUS, blank=True, default='m', help_text='Disponibilidad del libro')

    class Meta:
        ordering = ["debidoderegresar"] #ordering es un apuntador-identificador de palabra reservada de django para esta clase, no puedo usar el nombre "ordenar".
        permissions = (("puedeMarcarRetornado", "Colocar libro como retornado"),)

    @property
    def estaVencido(self):
        if self.debidoderegresar and date.today() > self.debidoderegresar:
            return True
        return False

    def __str__(self):
        """
        String para representar el Objeto del Modelo
        """
        #return '%s (%s)' % (self.id,self.libro.titulo)
        return f'{self.id} ({self.libro.titulo})' #Usando el formateo de cadena a partir de python 3.6

class Autor(models.Model):
    """
    Modelo que representa un autor
    """
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    nacimiento = models.DateField(null=True, blank=True)
    muerte = models.DateField('Muerte', null=True, blank=True)

    def get_absolute_url(self):
        """
        Retorna la url para acceder a una instancia particular de un autor.
        """
        return reverse('autorDetalles', args=[str(self.id)]) 

    def __str__(self):
        """
        String para representar el Objeto Modelo
        """
        return '%s, %s' % (self.apellido, self.nombre)

    class Meta:
        ordering = ['apellido']

class Lenguaje(models.Model):
    """
    Modelo que representa el lenguaje
    """
    nombre = models.CharField(max_length=100)

    def __str__(self):
        """
        String que representa al objeto Lenguaje
        """
        return self.nombre

catalogo/forms.py
from django import forms
from django.forms import ModelForm
from .models import LibroInstancia

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.

class ModeloFormRenovDeLibros(ModelForm):
    """
    Este es el formulario no consolidado (el que se presenta por primera vez). Se usa principalmente para limpiar y validar la fecha de renovación introducida por el usuario.
    Si solo necesita un formulario para asignar los campos de un solo modelo, entonces su modelo ya definirá la mayor parte de la información que necesita en su formulario: campos, etiquetas, texto de ayuda, etc. En lugar de recrear las definiciones de modelo en su formulario, usando el enfoque de usar un Form y la función view, es más fácil usar una clase auxiliar ModelForm como hacemos aquí, para crear el formulario a partir de su modelo. La gran ventaja de usar ModelForm es que si tiene que usar muchos campos, puede reducir la cantidad de código de manera bastante significativa.
    Ahora, en formularios raros muy complejos, no genéricos con uso de multiples modelos, usamos el enfoque Form-función view.
    """
    def clean_debidoderegresar(self):
        fecha = self.cleaned_data['debidoderegresar']
        #Nota para el enfoque ModelForm (el que estamos usando): la propiedad método debe llamarse como nombre reservado django, clean_nombredelcampoenelmodelo,
#en este caso, clean_debidoderegresar, y el self.cleaned_data['nombredelcampoenelmodelo'], es decir, self.cleaned_data['debidoderegresar'] tanto aquí como en su vista respectiva, renovacionLibroPorLibrero.

        if fecha < datetime.date.today():
            raise ValidationError(_('Fecha inválida - renovación al pasado!!!'))

        #Check date is in range librarian allowed to change (+4 weeks).
        if fecha > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Fecha inválida - renovación más allá de las 4 semanas'))

        # Remember to always return the cleaned fecha.
        return fecha

    class Meta:
        model = LibroInstancia
        #Configuramos los campos del modelo que vamos a utilizar:
        fields = ['debidoderegresar',]
        labels = { 'debidoderegresar': _('Fecha de renovación'), }
        help_texts = { 'debidoderegresar': _('Introduzca una fecha entre ahora y 4 semanas arriba (lo normal son 3).'), }
        #Para hacer un widget de introducción de fecha tipo calendario sólo de selección, usamos forms.DateInput con los atributos type en date y onkeydown en return false:
        widgets = {'debidoderegresar': forms.DateInput(attrs={'type': 'date', 'onkeydown': 'return false', 'placeholder': 'YYYY-MM-DD'}),}

catalogo/templates/autorYsusLibros.html
{% extends "base1.html" %}

{% block content %}

<p>Lista de libros del autor id 1<strong>{{ autor_context }}</strong>: {{ sus_libros }}</p>
<p>Autores: {{ autores_contx }}</p>

{% if autores_contx %}

<select class="w3-select w3-border" id="miSeleccion" onchange="mostrarValor(this.value)" style="width:50%">
    <option value="" disabled selected>Escoje el autor</option>
    <!-- Nota: en value puedo prescindir de las comillas, si no dejo espacio entre las llaves, así: value={{objeto.get_absolute_url}} -->
    {% for objeto in autores_contx %}
    <option value="{{ objeto.get_absolute_url }}">{{ objeto }}</option>
    {% endfor %}
</select>
{% else %}  
  <p>No hay autores.</p>
{% endif %}

<script>
//Claro, podemos usar onchange="window.location.href = this.value" en el elmento <select>, en lugar de esta función, y es más conciso:  
function mostrarValor(url) {
    window.location.href = url;
}
</script>

{% endblock %}

catalogo/templates/base1-inicio.html
{% extends "base1.html" %}<!--Heredado o extendido de base1.html -->

{% block content %}
<div class="w3-panel w3-red">
<p><h1>Librería versión no paginada</h1></p>
</div>
<div class="w3-container">
  <p>Bienvenido a la <em>biblioteca local</em>, un website muy básico desarrollado en el framework backend django,por Mozilla Developer Network.</p>
<div class="w3-container">
  <div class="w3-card-4" style="width:50%; margin:auto;">
  <ul class="w3-ul">
    <li><h3>Estadísticas de la librería:</h3></li>
    <li><strong>Libros:</strong> {{ cant_libros }}</li>
    <li><strong>Copias:</strong> {{ cant_instancias }}</li>
    <li><strong>Copias disponibles:</strong> {{ cant_inst_dispon }}</li>
    <li><strong>Autores:</strong> {{ cant_autores }}</li>
    <li><strong>Generos:</strong> {{ cant_generos }}</li>
  </ul>
  </div>
</div> 
 
<div class="w3-container">
<p>Has visitado esta página {{ cantVisitas }}{% if cantVisitas == 1 %} vez {% else %} veces {% endif %}. <a href="{% url 'resetearVisitas' %}">Reestablecer contador</a></p>
</div>

{% endblock %}

catalogo/templates/base1.html
{% load static %} <!-- Sin esta etiqueta no se cargará el favicon que está en el directorio de los estáticos. -->
<!DOCTYPE html>
<html>
<title>LibreríaLocalMain</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Link para el favicon: -->
<link rel="icon" type="image/svg" href="{% static '/images/djangoIco.svg' %}">
<!-- Link para css: -->
<link rel="stylesheet" href="https://www.w3schools.com/w3css/5/w3.css">
<script src="https://www.w3schools.com/lib/w3.js"></script>

<body class="w3-container">
  <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:23%">
      {% block barraLateral %}
      <h3 class="w3-bar-item">Menu</h3>
      <a href="{% url 'vistaHome' %}" class="w3-bar-item w3-button">Home</a>
      <a href="{% url 'todosLoslibros' %}" class="w3-bar-item w3-button">Todos los libros</a>
      <a href="{% url 'librosConBarbara' %}" class="w3-bar-item w3-button">Libros con Barbara</a>
      <a href="{% url 'toditicosLosAutores' %}" class="w3-bar-item w3-button">Todos los autores</a>
      <a href="{% url 'vistaLibrosDelAutor' %}" class="w3-bar-item w3-button">Uso de w3.css select-option y vista basada en función para enlazar a las vistas genéricas de detalle de autor</a>
      <a href="{% url 'vistaLibrosDelAutorFormulario' argumento=2 %}" class="w3-bar-item w3-button">Vista Autor y sus libros visualizada con formulario basado en función, en vez del método autor.libro_set.all en la plantilla</a>

      <!-- Hacemos un solucionador de url a nivel de la aplicación para ir a admin, que se encuentra en la base o entrada del proyecto, con fines didácticos. Sería un disparate hacerlo en producción. Para ello usamos la etiqueta reservada, admin:index: -->
      <a href="{% url 'admin:index' %}" class="w3-bar-item w3-button">Ir a admin</a>
      <a href="{% url 'resetearVisitas' %}" class="w3-bar-item w3-button">Reestablecer contador</a>
          {% if user.is_authenticated %}
            <span class="w3-bar-item">Usuario: {{ user.get_username }} {% if user.groups.all.0.name == "bibliotecarios" %} es bibliotecario {% if user.is_staff %} y perteneca al staff (puede eliminar libros y autores){% endif %}{% else %} y es un usuario normalito{% endif %}</span>
            
      <a href="{% url 'misLibrosalquilados' user.get_username %}" class="w3-bar-item w3-button">Libros en manos de {{ user.get_username }} </a>
      <a href="{% url 'logout' %}?next = {{ request.path }}" class="w3-bar-item w3-button">Cerrar sesión</a>      
            {% if perms.catalogo.puedeMarcarRetornado %}
              <hr>
              <span class="w3-bar-item">Bibliotecario</span>
              <a href="{% url 'librosAlquiladosActualmente' %}" class="w3-bar-item w3-button">Todos los libros prestados actualmente por la biblioteca</a>
              <a href="{% url 'crearautorini' %}" class="w3-bar-item w3-button">Crear Autor</a>
              <a href="{% url 'crearlibro' %}" class="w3-bar-item w3-button">Crear Libro</a>
    
              {% endif %}
          {% else %}
    
              <a href="{% url 'login' %}?next = {{ request.path }}" class="w3-bar-item w3-button">Iniciar sesión</a>
       {% endif %}   
        
       <!-- Pegamos dos etiquetas contiguas con flexboxs: -->
       <div class="w3-container">
         <div class="w3-flex" style="gap:8px">
           <div class="w3-padding w3-green"><h3>1</h3></div>

           <div class="w3-card-4">
            <header class="w3-container w3-blue">
              <h5>Encabezado</h5>
            </header>
           
            <div class="w3-container">
              <p>Esta es una etiqueta con sombra 4.</p>
            </div>

            <footer class="w3-container w3-blue">
              <h5>Pie</h5>
            </footer>
         </div>  
       </div>
       </div>
      <!-- Fin del bloque barra lateral: -->  
      {% endblock %}
  </div>

<!-- Bloque de contenido principal: -->

  <div style="margin-left:25%">
      <div class="w3-container w3-teal">
      <h1>Librería Local No Paginada</h1>
      </div>

      <!-- Bloque para sobreescribir en la plantilla heredera o hija -->
      {% block content %}{% endblock %}

      <!-- Comienzo bloque de implementación de la paginación: -->
      
      <!-- Fin división contenido principal -->
  </div>
    
</body>
</html>

catalogo/templates/formAutorYsusLibros.html
{% extends "base1.html" %}

{% block content %}
<br>
<form action="" method="get">
  <label>Autor: </label>
  <input
    id="miInput"
    type="text"
    name="argumento"
    placeholder="Ingrese indice autor" />
  
  <input type="submit" value="Siguiente" />
</form>

<p>Autor: {{ autor_context }}</p>
<p>Lista de sus libros: {{ sus_libros }}</p>

<script>
//Claro, podemos usar onchange="window.location.href = this.value" en el elmento <select>, en lugar de esta función, y es más conciso:  
//function nombre(argumento) {document.getElementById('miInput').value = 3;}
</script>

{% endblock %}