catalogo/urls.py
from django.urls import path
from . import views
from django.contrib import admin #Aunque no se vé el uso del admin aquí, si no lo importo se presenta la excepción "LookupError: No installed app with label 'admin'".

urlpatterns = [path('', views.inicio, name='vistaHome'), path('libros/', views.LibroVistaLista.as_view(), name='todosLoslibros'), path('libros/conbarbara', views.LibroVistaListaConBarbara.as_view(), name='librosConBarbara'), path('libro/<int:pk>', views.VistaDetalleLibro.as_view(), name='detallesDeLibro'), path('autores/', views.VistaListaGenAutores.as_view(), name='toditicosLosAutores'), path('autor/<int:pk>', views.VistaDetalladaGenAutor.as_view(), name='autorDetalles'), path('reseteoContSesiones', views.borrarConteoVisitas, name='resetearVisitas'),]

urlpatterns += [
    path('LibrosEnManosDelUsuario/<str:username>', views.ListaLibrosPrestadosAlUsuario.as_view(), name='misLibrosalquilados'),
]
#Note la variable de url para url dinámica, <str:username>
urlpatterns += [
    path('TodosLosLibrosActualmenteAlquilados/', views.ListaDeLibrosPrestadosActualmente.as_view(), name='librosAlquiladosActualmente'),
]

urlpatterns += [
    path('libro/<uuid:claveprimaria>/renovacion/', views.renovacionLibroPorLibrero, name='renovDeLibroPorLibrero'),
]

urlpatterns += [
    path('autor/crear/', views.CrearAutor.as_view(), name='crearautorini'),
    path('autor/<int:pk>/actualizar/', views.ActualizarAutor.as_view(), name='actualizarEsteAutor'), path('autor/<int:pk>/borrar/', views.BorrarAutor.as_view(), name='borrar-autor'),]
# Debemos usar pk como el nombre de nuestro valor de clave principal (primary key) capturado, ya que este es el nombre del parámetro esperado por las clases de vista de ediciones genéricas implementadas para ello.

urlpatterns += [
    path('libro/crear/', views.CrearLibro.as_view(), name='crearlibro'),
    path('libro/<int:pk>/actualizar/', views.ActualizarLibro.as_view(), name='actualizarLibro'), path('libro/<int:pk>/borrar/', views.BorrarLibro.as_view(), name='borrarlibro'),]

#Esta vista dejó de trabajar repentinamente:
#urlpatterns += [path('listaLibroautor/', views.VistaCombAutorLibro.as_view(), name='vistaListaLibrosAutor'),]

urlpatterns += [path('ejemUsoSelectOptionsW3.css/', views.librosDelAutor, name='vistaLibrosDelAutor'),]

urlpatterns += [path('librosDelAutor/<str:argumento>', views.formularioLibrosDelAutor, name='vistaLibrosDelAutorFormulario'),]

librerialocal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
from django.conf import settings
# Use static() to add url mapping to serve static files during development (only)
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),path('catalogo/', include('catalogo.urls')),path('', RedirectView.as_view(url='/catalogo/', permanent=True)),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),]
#El nombre url accounts no puede ser arbitrario, porque django en sus vistas genéricas utiliza este nombre en su implementación.

catalogo/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


# Create your models here.

class Genero(models.Model):
    """
    Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.).
    """
    nombre = models.CharField(max_length=200, help_text="Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.)")

    def __str__(self):
        """
        Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)
        """
        return self.nombre

from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Libro(models.Model):
    """
    Modelo que representa un libro (pero no un Ejemplar específico).
    """
    titulo = models.CharField(max_length=200)
    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
    descripcion = models.TextField(max_length=1000, help_text="Ingrese una breve descripción del libro")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genero = models.ManyToManyField(Genero, help_text="Seleccione un genero para este libro")
    lenguaje = models.ForeignKey('Lenguaje', on_delete=models.SET_NULL, null=True)
   
    def __str__(self):
        """
        String que representa al objeto Book
        """
        return self.titulo
#El método get_absolute_url para usarlo en las plantillas como href="{{ objeto.get_absolute_url }}", es generalmente preferible porque crea dinamicamente URLs más genéricas y fáciles de mantener en el código del modelo,
#mientras que la etiqueta {% url 'nombreRefDelaUrlEnPath' objeto.id %} es una forma directa de usar estas URLs dentro de las plantillas. get_absolute_url() se enfoca en la lógica de la URL en
#el modelo y es esencial para la integración con la aplicación de administración de Django y la generación de enlaces absolutos:
    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Book
        """
        return reverse('detallesDeLibro', args=[str(self.id)])

    class Meta:
        ordering = ['titulo', 'autor']

    def mostrar_genero(self):
    #Creates a string for tre in Admin.
        return ', '.join([ genero.nombre for genero in self.genero.all()[:3] ]) 

    mostrar_genero.short_description = 'Genero'

import uuid # Requerida para las instancias de libros únicos
from django.core.validators import MaxValueValidator, MinValueValidator 

class LibroInstancia(models.Model):
    """
    Modelo que representa una copia específica de un libro (i.e. que puede ser prestado por la biblioteca).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este libro particular en toda la biblioteca")
    libro = models.ForeignKey('Libro', on_delete=models.SET_NULL, null=True)
    imprenta = models.CharField(max_length=200)
    debidoderegresar = models.DateField(null=True, blank=True)
    prestatario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    PRESTAMO_STATUS = (
        ('m', 'Mantenimieno'),
        ('p', 'En prestamo'),
        ('d', 'Disponible'),
        ('r', 'Reservado'),
    )

    estatus = models.CharField(max_length=1, choices=PRESTAMO_STATUS, blank=True, default='m', help_text='Disponibilidad del libro')

    class Meta:
        ordering = ["debidoderegresar"] #ordering es un apuntador-identificador de palabra reservada de django para esta clase, no puedo usar el nombre "ordenar".
        permissions = (("puedeMarcarRetornado", "Colocar libro como retornado"),)

    @property
    def estaVencido(self):
        if self.debidoderegresar and date.today() > self.debidoderegresar:
            return True
        return False

    def __str__(self):
        """
        String para representar el Objeto del Modelo
        """
        #return '%s (%s)' % (self.id,self.libro.titulo)
        return f'{self.id} ({self.libro.titulo})' #Usando el formateo de cadena a partir de python 3.6

class Autor(models.Model):
    """
    Modelo que representa un autor
    """
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    nacimiento = models.DateField(null=True, blank=True)
    muerte = models.DateField('Muerte', null=True, blank=True)

    def get_absolute_url(self):
        """
        Retorna la url para acceder a una instancia particular de un autor.
        """
        return reverse('autorDetalles', args=[str(self.id)]) 

    def __str__(self):
        """
        String para representar el Objeto Modelo
        """
        return '%s, %s' % (self.apellido, self.nombre)

    class Meta:
        ordering = ['apellido']

class Lenguaje(models.Model):
    """
    Modelo que representa el lenguaje
    """
    nombre = models.CharField(max_length=100)

    def __str__(self):
        """
        String que representa al objeto Lenguaje
        """
        return self.nombre

catalogo/forms.py
from django import forms
from django.forms import ModelForm
from .models import LibroInstancia

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.

class ModeloFormRenovDeLibros(ModelForm):
    """
    Este es el formulario no consolidado (el que se presenta por primera vez). Se usa principalmente para limpiar y validar la fecha de renovación introducida por el usuario.
    Si solo necesita un formulario para asignar los campos de un solo modelo, entonces su modelo ya definirá la mayor parte de la información que necesita en su formulario: campos, etiquetas, texto de ayuda, etc. En lugar de recrear las definiciones de modelo en su formulario, usando el enfoque de usar un Form y la función view, es más fácil usar una clase auxiliar ModelForm como hacemos aquí, para crear el formulario a partir de su modelo. La gran ventaja de usar ModelForm es que si tiene que usar muchos campos, puede reducir la cantidad de código de manera bastante significativa.
    Ahora, en formularios raros muy complejos, no genéricos con uso de multiples modelos, usamos el enfoque Form-función view.
    """
    def clean_debidoderegresar(self):
        fecha = self.cleaned_data['debidoderegresar']
        #Nota para el enfoque ModelForm (el que estamos usando): la propiedad método debe llamarse como nombre reservado django, clean_nombredelcampoenelmodelo,
#en este caso, clean_debidoderegresar, y el self.cleaned_data['nombredelcampoenelmodelo'], es decir, self.cleaned_data['debidoderegresar'] tanto aquí como en su vista respectiva, renovacionLibroPorLibrero.

        if fecha < datetime.date.today():
            raise ValidationError(_('Fecha inválida - renovación al pasado!!!'))

        #Check date is in range librarian allowed to change (+4 weeks).
        if fecha > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Fecha inválida - renovación más allá de las 4 semanas'))

        # Remember to always return the cleaned fecha.
        return fecha

    class Meta:
        model = LibroInstancia
        #Configuramos los campos del modelo que vamos a utilizar:
        fields = ['debidoderegresar',]
        labels = { 'debidoderegresar': _('Fecha de renovación'), }
        help_texts = { 'debidoderegresar': _('Introduzca una fecha entre ahora y 4 semanas arriba (lo normal son 3).'), }
        #Para hacer un widget de introducción de fecha tipo calendario sólo de selección, usamos forms.DateInput con los atributos type en date y onkeydown en return false:
        widgets = {'debidoderegresar': forms.DateInput(attrs={'type': 'date', 'onkeydown': 'return false', 'placeholder': 'YYYY-MM-DD'}),}

catalogo/templates/catalogo/autor_confirm_delete.html
{% extends "base1.html" %}

{% block content %}

<h1>Borrar Autor</h1>

<p>Estas seguro de querer borrar el autor: {{ autor }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Si, borrar." />
</form>

{% endblock %}

catalogo/templates/catalogo/autor_detail.html
{% extends "base1.html" %}

{% block content %}
  <h1>Autor: {{ autor }} <span style="font-family: Arial; font-size: 18px; color: blue;">(autor.id:{{ autor.id }})</span></h1>
  <p><strong>{{ autor.nacimiento }}-{{ autor.muerte }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Libros</h4> 
    <!-- autor.libro_set.all es un método "automágicamente" creado por Django para devolver el conjunto de registros (instancias) del modelo Libro, asociado con una instancia o registro del modelo Autor, en particular. Este método es necesario porque has declarado un campo ForeignKey (uno-a-muchos) únicamente en el lado "muchos" (modelo Libro) de la relación. Como no haces nada para declarar la relación en el otro lado "uno" (modelo Autor), este no tiene ningún campo para obtener el conjunto de registros asociados. Para superar este problema, Django construye una función apropiadamente llamada "búsqueda reversa" que puedes usar. La función se construye convirtiendo a minúsculas el nombre del modelo de la clave primaria (lado 1), punto, el nombre del modelo en minúscula donde la ForeignKey fue declarada (lado muchos), seguido por _set. Así, la función creada es: autor.libro_set()). Se lee: conjunto de libros del autor: -->
    {% for libro in autor.libro_set.all %}
    <hr>
    <p><a href="{{libro.get_absolute_url}}">{{ libro }}</a> (libro.id:{{ libro.id }})</p>
    <p class="text-muted">{{ libro.descripcion }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalogo/templates/catalogo/autor_form.html
{% extends "base1.html" %}

{% block content %}
<div class="w3-panel w3-sand w3-tiny" style="width:50%; margin:auto;">
<div class="w3-card-4">
  <div class="w3-panel w3-brown">
    <h2>Datos</h2>
  </div>
  <form class="w3-container" method="post">
    {% csrf_token %}
    <label class="w3-text-blue">Nombre</label>
    <input
      class="w3-input w3-border w3-animate-input"
      id="id_nombre"
      name="nombre"
      type="text"
      value=""
      style="width:30%"
      required>
    <label class="w3-text-blue">Apellido</label>
    <input
      class="w3-input w3-border w3-animate-input"
      id="id_apellido"
      name="apellido"
      type="text"
      value="" 
      style="width:30%"
      required>
    <label class="w3-text-blue">Nacimiento</label>
    <input
      class="w3-input w3-border"
      id="id_nacimiento"
      name="nacimiento"
      type="date"
      value=""
      style="width:30%"
      onkeydown="return false"
      required>
    <label class="w3-text-blue">Muerte</label>
    <input
      class="w3-input w3-border"
      id="id_muerte"
      name="muerte"
      type="date"
      value=""
      style="width:30%"
      onkeydown="return false">

    <div class="w3-panel">
    {% if request.path == "/catalogo/autor/crear/" %} <input type="submit" class="w3-button w3-border w3-black"  value="Crear"> {% else %} <input type="submit" class="w3-button w3-border w3-black"  value="Actualizar">{% endif %}
    </div>
   </form>
</div>
<p>La URL actual es: {{ request.path }}</p>
<p>Usuario: {{ user.get_username }}</p>
<p>Usuario objeto: {{ user }}</p>
</div>

{% endblock %}

catalogo/templates/catalogo/autor_list.html
{% extends "base1.html" %}

{% block content %}
    <h1>Lista de Autores</h1>

    {% if autor_list %}
    <br>
    
    <input oninput="w3.filterHTML('#id01', 'li', this.value)" class="w3-input w3-light-gray" placeholder="Búsqueda por nombre de autor:">
    <ul id="id01" class="w3-ul w3-margin-top w3-border">
    {% for objetoX in autor_list %}
      <li>
        <a href="{{objetoX.get_absolute_url}}">
        <!-- Recuerde que el objeto retorna la propiedad nombre y apellido con el su atributo método __str__(self): return '%s, %s' % (self.apellido, self.nombre) -->
      {{ objetoX }} </a>(id:{{ objetoX.id }}) ({{ objetoX.nacimiento }} - {% if objetoX.muerte %}{{objetoX.muerte}}{% endif %}) {% if perms.catalogo.puedeMarcarRetornado %}<a href="{% url 'actualizarEsteAutor' objetoX.id %}">Actualizar</a> {% endif %}{% if user.is_staff %}<a href="{% url 'borrar-autor' objetoX.id %}">-Borrar</a>{% endif %}
      </li>
      {% endfor %}
    </ul>

    <p>Variable de contexto autor_list: {{autor_list}}</p>
    
    <br>
    {% else %}  
      <p>No hay libros en la biblioteca.</p>
    {% endif %}
    <br>
    <p><a href="{% url 'librosConBarbara' %}">Libros con barbara</a></p>
{% endblock %}

catalogo/templates/catalogo/combina_LibroAutor.html
{% extends "base1.html" %}

{% block content %}

<h2>Lista de autores actuales en la biblioteca:</h2>
<ul>
    <!-- Aquí vemos la importancia y vigencia de la función de etiquetas para plantillas del tipo {% url nombreUrl parámetro %}, puesto que debemos enviar un parámetro al url específicado, que no tiene un enlace explícito o visible para clikear a la vista y plantilla a usar: -->
    {% for objeto in objetos_combinados %}
        <li>{{ objeto }}</li>
    {% endfor %}
</ul>

<!--
<h2>Lista de libros actuales en la biblioteca:</h2>
<ul>
    {% for itemLibro in listaDeLibros %}
        <li>{{ itemLibro }}</li>
    {% endfor %}
</ul> -->

{% endblock %}

catalogo/templates/catalogo/formularioRenovacion.html
{% extends "base1.html" %}
{% block content %}

    <h1>Renovar: {{instanciaDeLibro.libro.titulo}}</h1>
    <p>Prestatario: {{instanciaDeLibro.prestatario}}</p>
    <p{% if instanciaDeLibro.estaVencido %} class="text-danger"{% endif %}>Debió regresar el: {{instanciaDeLibro.debidoderegresar}}</p>

    <form action="" method="post">
        {% csrf_token %}
        
        {{ formulario }}
        
        <input type="submit" value="Renovar" />
    </form>

{% endblock %}

catalogo/templates/catalogo/libro_confirm_delete.html
{% extends "base1.html" %}

{% block content %}

<h1>Borrar Libro</h1>

<p>Estas seguro de querer eliminar el libro: {{ libro }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Si, eliminar" />
</form>

{% endblock %}

catalogo/templates/catalogo/libro_detail.html
{% extends "base1.html" %}

{% block content %}
  <h1>Titulo: {{ libro }} <span style="font-family: Arial; font-size: 18px; color: blue;">(libro.id:{{ libro.id }})</span></h1>
<!-- Recuerde que la variable de contexto es el nombre del modelo en minúsculas, en este caso, libro -->
<!-- {{ libro.autor.get_absolute_url }} es igual a {% url 'autorDetalles' libro.autor.pk %} la primera proposición es más concisa y robusta.-->
  <p><strong>Autor:</strong> <a href="{{libro.autor.get_absolute_url}}">{{ libro.autor }}</a> (libro.autor.id:{{libro.autor.id}}) libro.id:{{libro.id}}</p> <!-- enlace de detalle del autor: el url es el name que definimos para el mapeador path('autor/<int:pk>', views.VistaDetalladaGenAutor.as_view(), name='detallesAutor') -->
  <p><strong>Resumen:</strong> {{ libro.descripcion }}</p>
  <p><strong>ISBN:</strong> {{ libro.isbn }}</p>
  <p><strong>Idioma:</strong> {{ libro.lenguaje }}</p>
  <p><strong>Genero:</strong> {% for objReturnSelfNombre in libro.genero.all %} {{objReturnSelfNombre}}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copias</h4>
    <!-- libro.libroinstancia_set.all es un método "automágicamente" creado por Django para devolver el conjunto de registros (instancias) del modelo LibroInstancia, asociado con una instancia o registro del modelo Libro, en particular. Este método es necesario porque has declarado un campo ForeignKey (uno-a-muchos) únicamente en el lado "muchos" (modelo LibroIntancia) de la relación. Como no haces nada para declarar la relación en el otro lado "uno" (modelo Libro), este no tiene ningún campo para obtener el conjunto de registros asociados. Para superar este problema, Django construye una función apropiadamente llamada "búsqueda reversa" que puedes usar. La función se construye escribiendo en minúsculas el nombre del modelo dónde está la clave principal (lado de 1), punto, nombre en minúscula del modelo donde la ForeignKey fue declarada (lado muchos), seguido por _set. Así, la función creada es: libro.libroinstancia_set()). Se lee: conjunto de las copias (libroinstancias) para ese libro: -->
    {% for copia in libro.libroinstancia_set.all %}
    <hr>
    <p class="{% if copia.estatus == 'd' %}text-success{% elif copia.estatus == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copia.get_estatus_display }}</p>
    {% if copia.estatus == 'p' %}<p><strong>Pendiente de devolución:</strong> {% if not copia.estaVencido %}{{copia.debidoderegresar}} {% else %} el usuario de nombre "{{copia.prestatario}}" (id.{{copia.prestatario.id}}) debió regresarlo el {{ copia.debidoderegresar }} ... no ha regresado el libro aún!!! {% endif %}</p>{% endif %}<!--Note cómo podemos llegar hasta el id del usuario, prestatario de la instancia de libro (copia.prestatario.id), a través de un elemento de libro.libroinstancia_set.all: con django se hace fácil e intuitivo acceder a los valores de los campos de las intancias de sus modelos correspondientes.--> 
    <p><strong>Imprenta:</strong> {{copia.imprenta}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copia.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalogo/templates/catalogo/libro_form.html
{% extends "base1.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Crear" />

</form>
{% endblock %}

catalogo/templates/catalogo/librosConBarbara.html
{% extends "base1.html" %}

{% block content %}

    <h1>Lista de libros con Barbara</h1>

    {% if listaDeLibrosConBarbara %}

    <ul>
      
      {% for objeto in listaDeLibrosConBarbara %}

      <li>
        <!-- Usamos href="{% url 'detallesDeLibro' objeto.id %}" en vez de href="{{ objeto.get_absolute_url }}" para este caso, con fines didáctico: sabemos que es preferible usar el método get_absolute_url que implementamos en el código de este modelo para este tipo de url dinámicas que tienen parámetros. -->
        
        <a href="{% url 'detallesDeLibro' objeto.id %}">{{ objeto.titulo }}</a> ({{objeto.autor}}) <br> Retorno del método objeto.get_absolute_url o la función url 'detallesDeLibro' objeto.id: {{objeto.get_absolute_url}}
      </li>
        
      {% endfor %}
      <br>-La variable de contexto principal declarada para esta vista genérica, context_object_name = 'listaDeLibrosConBarbara': {{listaDeLibrosConBarbara}}
      <br>-La variable de contexto adicional 'una2daVariableDeContexto': {{una2daVariableDeContexto}}
      <br>-Y la variable de contexto, 'variableDeContextoN' (50+25+3.1415+200+500): {{variableDeContextoN}}

       {% comment %} Cuando queremos generar la url dinamicamente de un enlace a una página, la única opción es la etiqueta de función {% url 'nombreDeLaUrlEnFunciónPath' %}. Observación: no puedo comentar este texto con las etiquetas html de comentar, <!-- -->, porque me lee la etiqueta de función url y me envia el error "no se encuentra el reverso para 'nombreDeLaUrlEnFunciónPath'. Averiguar por qué pasa esto.{% endcomment %}
    </ul>
    
    {% else %}
      <p>No hay libros en la biblioteca con barbara en su título.</p>
    {% endif %}
{% endblock %}

catalogo/templates/catalogo/listaInstanciasDeLibrosPrestadasAlUsuario.html
{% extends "base1.html" %}

{% block content %}
    <h1>Libros prestados a {{user.get_username}} <span style="font-size: 18px">({% if user.is_staff %}Usuario staff id.{{user.id}}{% else %}id. {{user.id}}{% endif %})</span></h1>

    {% if libroinstancia_list %}
    <ul>

      {% for instanciaDeLibro in libroinstancia_list %}
      <li class="{% if instanciaDeLibro.estaVencido %}text-danger{% endif %}">
        <a href="{{ instanciaDeLibro.libro.get_absolute_url }}">{{instanciaDeLibro.libro}}</a> {% if not instanciaDeLibro.estaVencido %} Debe regresarlo el {{ instanciaDeLibro.debidoderegresar }}) {% else %} Debió regresarlo el {{ instanciaDeLibro.debidoderegresar }} ... no ha regresado el libro aún!!!{% endif %}
<!-- Recuerde que la propiedad get_absolute_url del libro al que pertenece el objeto de modelo LibroInstancia, instanciaDeLibro, retorna reverse('detallesDeLibro', args=[str(self.id)]), y  libro, self.titulo -->
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay libros prestados para este usuario.</p>
    {% endif %}
{% endblock %}

catalogo/templates/catalogo/todosLosLibros.html
{% extends "base1.html" %}

{% block content %}
    <h1>Lista de libros</h1>

    {% if mi_listaDeLibros %}
    
    <input oninput="w3.filterHTML('#id01', 'li', this.value)" class="w3-input w3-light-gray" placeholder="Búsqueda libro por nombre:">
    <ul id="id01" class="w3-ul w3-margin-top w3-border">
    {% for objetoNomArbitr in mi_listaDeLibros %}
      <li>
        <!-- Recuerde que el objeto retorna la propiedad titulo del modelo Libro con su atributo método __str__(self): return self.titulo -->
        <a href="{{ objetoNomArbitr.get_absolute_url }}">{{ objetoNomArbitr }}</a> ({{objetoNomArbitr.autor}} id autor:{{ objetoNomArbitr.autor.id }}) (id libro:{{ objetoNomArbitr.id }}) {% if perms.catalogo.puedeMarcarRetornado %}<a href="{% url 'actualizarLibro' objetoNomArbitr.id %}">Actualizar</a> {% endif %}{% if user.is_staff %}<a href="{% url 'borrarlibro' objetoNomArbitr.id %}">-Borrar</a>{% endif %}
<!-- Recuerde que este hipervínculo (href), llama al método get_absolute_url(self) del modelo que se está utilizando, en este caso, Libro, que retorna reverse('detallesDeLibro', args=[str(self.id)])  -->
      </li>
      {% endfor %}
    </ul>
    <br>
    <br>
    <p>Variable de contexto mi_listaDeLibros: {{ mi_listaDeLibros }}</p>
    </ul>
    <br>
    {% else %}  
      <p>No hay libros en la biblioteca.</p>
    {% endif %}
    <br>
    <p><a href="{% url 'librosConBarbara' %}">Libros con barbara</a></p>
{% endblock %}

catalogo/templates/catalogo/todosLosLibrosPrestadosActualmente.html
{% extends "base1.html" %}

{% block content %}
    <h1>Libros que Están Prestados Actualmente</h1>

    {% if libroinstancia_list %}
    <ul>
      {% for instanciaDeLibro in libroinstancia_list %}
        
          <li class="{% if instanciaDeLibro.estaVencido %}text-danger{% endif %}">
          <a href="{{ instanciaDeLibro.libro.get_absolute_url }}">{{instanciaDeLibro.libro}}</a> ({{ instanciaDeLibro.debidoderegresar }}) <span style="color: black;">- {{ instanciaDeLibro.prestatario }} (id.{{instanciaDeLibro.prestatario.id}}) </span> {% if perms.catalogo.puedeMarcarRetornado %}- <a href="{% url 'renovDeLibroPorLibrero' instanciaDeLibro.id %}">Renovar</a>  {% endif %}
<!-- Recuerde que la propiedad get_absolute_url del libro al que pertenece el objeto de modelo LibroInstancia, instanciaDeLibro, retorna reverse('detallesDeLibro', args=[str(self.id)]), y  libro, self.titulo -->
         
         </li>

      {% endfor %}
    </ul>

    {% else %}
      <p>No hay libros prestados actualmente en la biblioteca.</p>
    {% endif %}
{% endblock %}